In [11]:
import numpy as np

In [5]:
# ----- 기본 -----

In [6]:
# 배열 만들기
np.array([1,3,5])

array([1, 3, 5])

In [7]:
np.array(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 0으로 가득 찬 배열 만들기
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
# 단위행렬 만들기
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
np.eye(3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [12]:
np.eye(3, k=-1, dtype=int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [2]:
# 배열의 형태 알기
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a.shape

(3, 4)

In [14]:
np.size(a)

12

In [3]:
# 배열의 필요한 부분 자르기
a = np.array(['a','b',3,4])
a[1:3]

array(['b', '3'], dtype='<U1')

In [12]:
# 내용 수정하기
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[2,3] = 1
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  1]])

In [17]:
# 배열에 상수 연산
n1 = np.array([3,6,9])
n1+5

array([ 8, 11, 14])

In [18]:
# 배열끼리 연산
n2 = np.array([1,2,3])
n1+n2

array([ 4,  8, 12])

In [19]:
x = np.array([-1, -2])
np.abs(x)

array([1, 2])

In [13]:
np.max(a) # 최댓값인 원소를 반환

11

In [18]:
np.argmax(a) # 최댓값인 원소의 인덱스를 반환

10

In [19]:
a.argmax(axis=0) # 행방향으로(세로로) 비교했을 때 최댓값인 원소의 인덱스를 반환

array([2, 2, 2, 1])

In [20]:
a.argmax(axis=1) # 열방향으로(가로로) 비교했을 때 최댓값인 원소의 인덱스를 반환

array([3, 3, 2])

In [31]:
np.amax(a, axis=0, keepdims=True)

array([[ 9, 10, 11,  8]])

In [30]:
np.amax(a, axis=1, keepdims=True)

array([[ 4],
       [ 8],
       [11]])

In [12]:
np.min(a)

1

In [13]:
np.mean(a) # np.average도 가능

5.583333333333333

In [14]:
np.median(a)

5.5

In [15]:
np.var(a)

11.076388888888891

In [16]:
np.std(a)

3.32812092461931

In [2]:
np.sqrt(4)

2.0

In [5]:
# 올림 
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [8]:
# 요소 선택
a>=0

array([False, False, False,  True,  True,  True,  True])

In [9]:
(a>=0).sum()

4

In [10]:
(a>=0).sum().item() # np.array에서 int로 변환하기 위해 item 사용

4

In [7]:
a[a>=0]

array([0.2, 1.5, 1.7, 2. ])

In [20]:
# 슬라이싱
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [ ]:
# ----- trnasform -----

In [5]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1])

In [16]:
# reshape에서 -1의 의미 https://rfriend.tistory.com/345
x = np.arange(12)

In [17]:
x.reshape(-1, 1) # 12행 1열

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [18]:
x.reshape(-1, 3) # 4행 3열

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
x = np.arange(4)
x.shape, x

((4,), array([0, 1, 2, 3]))

In [26]:
x1 = x[np.newaxis, :]
x1.shape, x1

((1, 4), array([[0, 1, 2, 3]]))

In [27]:
x2 = x[:, np.newaxis]
x2.shape, x2

((4, 1),
 array([[0],
        [1],
        [2],
        [3]]))

In [35]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([1, 1, 1])
x1.shape, x2.shape

((5,), (3,))

In [36]:
x1 + x2 # 차원이 안 맞아서 에러

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [37]:
x1_new = x1[:, np.newaxis]
x1_new.shape, x1_new

((5, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5]]))

In [38]:
x1_new + x2

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [23]:
# ----- random -----

In [25]:
# np.random.randint - 균일분포의 정수 난수 생성
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
np.random.randint(1, 10) # 1부터 9까지 랜덤숫자1개

6

In [20]:
np.random.randint(low=0, high=5, size=(10,)) 

array([3, 4, 2, 4, 0, 3, 2, 4, 0, 2])

In [27]:
np.random.randint(5, size=(10,)) 

array([4, 1, 4, 4, 4, 2, 1, 1, 2, 0])

In [21]:
# np.random.rand(m, n) - 0~1에서 표준정규분포를 따르도록 mxn array 생성
np.random.rand(3, 2)

array([[0.25617515, 0.47264807],
       [0.77203779, 0.19276536],
       [0.27738271, 0.65777868]])

In [18]:
# np.random.randn(m, n) - 평균 0, 표준편차 1의 표준정규분포를 따르도록 mxn array 생성
np.random.randn(3,2)

array([[-1.23510046,  1.44568054],
       [ 1.31368347,  3.04118108],
       [-0.8549623 ,  1.96708225]])

In [19]:
# np.random.normal - 임의의 분포에서 숫자 추출
np.random.normal(loc=0, scale=1, size=10) # loc는 평균값, scale은 표준편차 지정

array([-1.03416653, -1.22795252, -1.94692057,  0.58842752,  0.4483711 ,
        1.15165056,  1.50711248, -0.2417824 ,  1.49437375,  0.39669625])

In [38]:
# 60% of "1" and 40% of "o"
x=[];

for t in range(10):
    if(np.random.rand() > 0.4):
        x.append(1.)
    else:
        x.append(0.)

x

[1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0]

In [37]:
# 임의로 정렬하기
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.random.permutation(x)

array([4, 2, 6, 3, 0, 7, 5, 1, 8])

In [24]:
np.random.permutation(10) # 해당 숫자까지의 배열을 만들고 무작위 정렬

array([1, 7, 6, 9, 2, 5, 4, 3, 8, 0])

In [46]:
# 임의의 수 고르기
np.random.choice(10, 3) # 0~9까지의 수 중에서 3개 뽑기

array([8, 2, 3])

In [4]:
# ----- random seed -----
# seed가 선언된 다음에 발생하는 rand method에서 미리 정해진 세트의 난수를 return
# 동일한 seed value끼리는 동일한 세트의 난수를 가지고 있어서 언제 어디서 실행해도 동일한 숫자를 return
# https://cosmosproject.tistory.com/444 

In [33]:
np.random.seed(seed = 0)
print(np.random.random(3))
np.random.seed(2)
print(np.random.random(3))
np.random.seed(0)
print(np.random.random(3))

[0.5488135  0.71518937 0.60276338]
[0.4359949  0.02592623 0.54966248]
[0.5488135  0.71518937 0.60276338]


In [5]:
# ----- 조건 -----

In [41]:
# if절처럼 사용하기
score = [60, 75, 85, 91, 100]
grade = []

for i in score:
    condlist = [i >= 90,
                (i < 90) & (i >= 80),
                i < 80]
    choicelist = ['A','B','C']
    grade.append(np.select(condlist, choicelist))
    
grade

[array('C', dtype='<U21'),
 array('C', dtype='<U21'),
 array('B', dtype='<U21'),
 array('A', dtype='<U21'),
 array('A', dtype='<U21')]

In [ ]:
# ----- 행렬 연산 -----

In [10]:
a = np.array([[1, 0], 
             [0, 1], 
             [1, 2]])
b = np.array([[4, 1], 
             [2, 2]])

In [15]:
a.shape, b.shape

((3, 2), (2, 2))

In [7]:
np.dot(a, b)

array([[4, 1],
       [2, 2],
       [8, 5]])

In [17]:
np.dot(b, a)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [16]:
np.matmul(a, b)

array([[4, 1],
       [2, 2],
       [8, 5]])

In [16]:
a = np.arange(2*2*3).reshape((2,2,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [17]:
b = np.arange(2*2*3).reshape((2,3,2))
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [18]:
np.dot(a, b)

array([[[[ 10,  13],
         [ 28,  31]],

        [[ 28,  40],
         [100, 112]]],


       [[[ 46,  67],
         [172, 193]],

        [[ 64,  94],
         [244, 274]]]])

In [21]:
np.dot(b, a)

array([[[[  3,   4,   5],
         [  9,  10,  11]],

        [[  9,  14,  19],
         [ 39,  44,  49]],

        [[ 15,  24,  33],
         [ 69,  78,  87]]],


       [[[ 21,  34,  47],
         [ 99, 112, 125]],

        [[ 27,  44,  61],
         [129, 146, 163]],

        [[ 33,  54,  75],
         [159, 180, 201]]]])

In [22]:
a.dot(b)

array([[[[ 10,  13],
         [ 28,  31]],

        [[ 28,  40],
         [100, 112]]],


       [[[ 46,  67],
         [172, 193]],

        [[ 64,  94],
         [244, 274]]]])

In [19]:
np.matmul(a, b)

array([[[ 10,  13],
        [ 28,  40]],

       [[172, 193],
        [244, 274]]])

In [23]:
np.matmul(b, a)

array([[[  3,   4,   5],
        [  9,  14,  19],
        [ 15,  24,  33]],

       [[ 99, 112, 125],
        [129, 146, 163],
        [159, 180, 201]]])

In [36]:
# 제곱
x1 = np.arange(6)
x2 = np.array([[1, 2, 3, 3, 2, 1], [1, 2, 3, 3, 2, 1]])

np.power(x1, x2)

array([[ 0,  1,  8, 27, 16,  5],
       [ 0,  1,  8, 27, 16,  5]])

In [13]:
# ----- Einsum -----

In [26]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# transpose
np.einsum("ij->ji", a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
# matrix sum to scalar
np.einsum("ij->", a)

21

In [29]:
# matrix column or row sum
np.einsum("ij->i", a)

array([ 6, 15])

In [30]:
np.einsum("ij->j", a)

array([5, 7, 9])

In [31]:
# diagonal, Trace
b = np.eye(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.einsum('ii->i', b)

array([1., 1., 1., 1.])

In [33]:
np.einsum('ii->', b)

4.0

In [37]:
x = np.array([-1, -10, -100])
y = np.array([1, 10, 100])

# Dot Product
np.einsum('i,i->', x, y)

-10101

In [38]:
# Outer product
np.einsum('i,j->ij', x,y)

array([[    -1,    -10,   -100],
       [   -10,   -100,  -1000],
       [  -100,  -1000, -10000]])

In [39]:
# element-wise product of vector
np.einsum('i,i->i', x, y)

array([    -1,   -100, -10000])

In [49]:
# element-wise product of matrix
a = np.arange(6).reshape((2, 3))
b = np.arange(6).reshape((2, 3))
a, b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [47]:
np.einsum('ij,ij->', a, b)

55

In [50]:
# Matrix-Vector multiplication
a = np.array([[1,2,3], [4,5,6]])
b = np.array([-1, -10, -100])
np.einsum('ij,j->i', a, b)

array([-321, -654])

In [51]:
# Matrix-Matrix Multiplication
a = np.array([[1,2,3], [4,5,6]])
b = a.transpose()
np.einsum('ik,kj->ij', a, b)

array([[14, 32],
       [32, 77]])

In [57]:
# Batched Matrix Multiplication
a = np.random.random(size=(3, 4, 3))
b = np.random.random(size=(3, 3, 2))
np.einsum('bik,bkj->bij',a, b)

array([[[0.96138752, 0.86772066],
        [1.37009053, 1.21854099],
        [1.09333588, 0.95441347],
        [0.74118228, 0.66563492]],

       [[0.31902837, 0.27022977],
        [0.41782602, 0.36268834],
        [0.5656566 , 0.20729255],
        [0.83685894, 0.43722301]],

       [[1.62794336, 0.67376576],
        [0.32813804, 0.66033983],
        [0.88305192, 0.32384935],
        [1.52667824, 0.58505251]]])