In [1]:
# ----- 텐서 만들기 -----
# tensor란 다차원 array로 쉽게 말해 행렬이라고 생각하면 된다!

In [2]:
import torch
import numpy as np

In [2]:
# 임의의 텐서 만들기

In [12]:
torch.Tensor(2,3) 

tensor([[8.4078e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [9]:
torch.rand(2,3)

tensor([[0.7769, 0.8737, 0.8399],
        [0.6711, 0.8999, 0.6666]])

In [3]:
# element를 직접 지정해서 만들기

In [13]:
torch.tensor([[1,2,3], [4,5,6]]) 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
torch.tensor(data=[1.0, 2.0], requires_grad=True) 
# float으로 입력해야 함
# requires_grad : 텐서에 대한 기울기를 저장할지 여부

tensor([1., 2.], requires_grad=True)

In [4]:
# numpy array에서 tensor로 바꾸기

In [33]:
n = np.array([[1,2],[3,4]])
type(n)

numpy.ndarray

In [34]:
t = torch.Tensor(n)
type(t)

torch.Tensor

In [5]:
# 0, 1로 채워진 텐서 만들기

In [24]:
# 2x2로 된 영행렬 만들기
torch.zeros(2, 2) 

tensor([[0., 0.],
        [0., 0.]])

In [25]:
# 2x2이고 모든 원소가 1인 행렬 만들기
torch.ones(2, 2) 

tensor([[1., 1.],
        [1., 1.]])

In [6]:
# 인자로 들어오는 텐서와 형태가 같으면서 0 혹은 1로 채워진 텐서 만들기

In [35]:
t = torch.rand(4,5)
t0 = torch.zeros_like(t)
t1 = torch.ones_like(t)

In [27]:
t0

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [28]:
t1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [7]:
# ----- 텐서 크기, 타입 확인 -----
# 데이터 타입 관련 참고글
# https://pytorch.org/docs/stable/tensors.html
# https://teddylee777.github.io/pytorch/pytorch-tensors-basic

In [40]:
t1 = torch.FloatTensor([[1,2], [3,4]])
t2 = t1.long()

In [8]:
# 텐서 타입 확인

In [30]:
t1.type() 

'torch.FloatTensor'

In [33]:
t2.type() 

'torch.LongTensor'

In [9]:
# 데이터 타입 확인

In [34]:
type(t1) 

torch.Tensor

In [35]:
type(t2)

torch.Tensor

In [10]:
# 텐서 사이즈 확인 (shape, size 모두 가능)

In [36]:
t1.shape 

torch.Size([2, 2])

In [37]:
t1.size()

torch.Size([2, 2])

In [38]:
t2.shape 

torch.Size([2, 2])

In [39]:
t2.size() 

torch.Size([2, 2])

In [11]:
# ----- 텐서 변형하기 -----

In [36]:
t = torch.rand(12,1) 
t.size()

torch.Size([12, 1])

In [12]:
# reshape, permute

In [40]:
t1 = t.reshape(3, 4, 1)
t2 = t1.permute(1, 2, 0) # 4, 1, 3

In [41]:
t1

tensor([[[0.7465],
         [0.3788],
         [0.4866],
         [0.4709]],

        [[0.8945],
         [0.2411],
         [0.8721],
         [0.5138]],

        [[0.0331],
         [0.0614],
         [0.8373],
         [0.5778]]])

In [65]:
t2

tensor([[[0.9262, 0.9110, 0.8328]],

        [[0.8126, 0.7399, 0.1617]],

        [[0.7536, 0.4401, 0.5982]],

        [[0.3720, 0.1115, 0.3234]]])

In [17]:
# squeeze, unsqueeze

In [67]:
# 1인 차원을 제거
t.squeeze().size()

torch.Size([12])

In [70]:
# 특정 위치에 1인 차원을 추가. 이 경우 두번째 차원에 1을 추가
t.unsqueeze(1).size()

torch.Size([12, 1, 1])

In [13]:
# view, view_as

In [38]:
# view: 넘파이에서의 Reshape와 같은 역할
# -1은 사용자가 잘 모르겠으니 일부 dimension만 지정해주고 나머지 dimensino은 파이토치에 맡기겠다는 의미
t.view([-1, 3])

tensor([[0.7465, 0.3788, 0.4866],
        [0.4709, 0.8945, 0.2411],
        [0.8721, 0.5138, 0.0331],
        [0.0614, 0.8373, 0.5778]])

In [42]:
# view_as: size가 12인 텐서t를 size가 3,4,1인 텐서t1처럼 나타내기
t.data.view_as(t1) 

tensor([[[0.7465],
         [0.3788],
         [0.4866],
         [0.4709]],

        [[0.8945],
         [0.2411],
         [0.8721],
         [0.5138]],

        [[0.0331],
         [0.0614],
         [0.8373],
         [0.5778]]])

In [14]:
# ----- 텐서 연산 -----

In [3]:
# 새로운 텐서 생성
t = torch.tensor([[1,2], [4,5]])

In [15]:
# sum
# https://velog.io/@reversesky/torch.sum에-대해-알아보자

In [74]:
# 텐서t의 모든 원소를 sum
torch.sum(t)

tensor(12)

In [78]:
# 특정 dim에 대하여 sum
t0 = torch.sum(t, dim=0, keepdim=True) # keepdim : 결과로 나오는 텐서가 차원을 그대로 유지하게 할 것인지
t0

tensor([[5, 7]])

In [79]:
t0.shape 

torch.Size([1, 2])

In [80]:
t1 = torch.sum(t, dim=1, keepdim=True) 
t1

tensor([[3],
        [9]])

In [82]:
t1.shape 

torch.Size([2, 1])

In [16]:
# max

In [23]:
t = torch.tensor([[1,2], [5,4]])
t

tensor([[1, 2],
        [5, 4]])

In [24]:
t.argmax(0)

tensor([1, 1])

In [25]:
t.argmax(1)

tensor([1, 0])

In [26]:
t.max(1) # 괄호 안의 숫자는 dimension을 의미

torch.return_types.max(
values=tensor([2, 5]),
indices=tensor([1, 0]))

In [27]:
t.max(0) 

torch.return_types.max(
values=tensor([5, 4]),
indices=tensor([1, 1]))

In [28]:
# 최대값인 원소
t.max(1)[0] 

tensor([2, 5])

In [29]:
# 최대값인 원소의 인덱스
t.max(1)[1] 

tensor([1, 0])

In [30]:
t.max(1)[0].shape 

torch.Size([2])

In [31]:
# keepdim 여부에 따라 사이즈가 달라짐
t.max(1, keepdim=True)[0].shape 

torch.Size([2, 1])

In [18]:
# eq: 각 원소가 같은지 다른지 비교하기

In [96]:
torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [False,  True]])

In [97]:
# 텐서t와 새로운 텐서를 비교
t.eq(torch.tensor([[1, 2], [3, 4]])) 

tensor([[ True,  True],
        [False, False]])

In [98]:
# True를 1로, False를 0으로 count해서 더함
t.eq(torch.tensor([[1, 2], [3, 4]])).sum() 

tensor(2)

In [19]:
# 그 외

In [99]:
# 각 원소를 제곱
torch.pow(t, 2) 

tensor([[ 1,  4],
        [16, 25]])

In [100]:
# exponential
torch.exp(t) 

tensor([[  2.7183,   7.3891],
        [ 54.5982, 148.4132]])

In [103]:
# sigmoid 계산
torch.sigmoid(t) # torch.special.expit(t)도 가능

tensor([[0.7311, 0.8808],
        [0.9820, 0.9933]])

In [102]:
# matrix multiplication : [n, m] x [m,p] = [n,p] 를 구현
torch.mm(t, t) 

tensor([[ 9, 12],
        [24, 33]])

In [104]:
# 벡터와의 연산
v = torch.ones((2,1)) # 만약 2x1 벡터가 아니라 3x1 벡터라면? 에러가 날 것이다!
t+v 

tensor([[2., 3.],
        [5., 6.]])

In [28]:
# ----- 두 개의 텐서 합치기 -----

In [24]:
t1 = torch.tensor([[1, 2],
                   [3, 4]])
t2 = torch.tensor([[5, 6],
                   [7, 8]])

In [30]:
torch.cat((t1, t2), dim=0) # dim=0인 경우

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [26]:
torch.cat((t1, t2), dim=1) # dim=1인 경우

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [27]:
torch.stack((t1, t2)) # dimension을 유지 하면서 붙여주는 것

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [20]:
# ----- 텐서 차원 축소 -----

In [107]:
t = torch.randn((2,3,4))
t

tensor([[[-0.3607,  0.4937, -0.6627, -0.0913],
         [-0.7442,  0.8280, -1.0501,  1.0707],
         [ 0.3615,  0.1537, -0.1103, -0.2793]],

        [[ 0.0159,  0.8725,  0.1054, -0.6958],
         [-0.5273,  0.5162,  0.7550, -0.1941],
         [-0.0901,  0.6055, -1.3508,  0.6819]]])

In [109]:
# argmax : 가장 큰 값을 가지는 index를 뽑는 함수 & dim=1은 1st dim에서 비교하겠다는 의미
t_argmax1 = torch.argmax(t, dim=1) 
t_argmax1

tensor([[2, 1, 2, 1],
        [0, 0, 1, 2]])

In [110]:
t_argmax1.shape

torch.Size([2, 4])

In [111]:
t_argmax2 = torch.argmax(t, 1, keepdims=True)

In [112]:
t_argmax2.shape

torch.Size([2, 1, 4])

In [21]:
# ----- GPU 사용 관련 -----

In [114]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [115]:
t.is_cuda 

False

In [116]:
t.device

device(type='cpu')

In [121]:
# 만약 GPU라면
# t_gpu = t.cuda(device)
# t_gpu.is_cuda 
# t_gpu.device