In [2]:
import torch
import torch.nn as nn

In [3]:
# ----- nn.Conv2d -----
# https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html
# torch.nn.Conv1D : convolution on 1 dimensional vector: input shape of (batch, channels, size)
# torch.nn.Conv2D : input shape: (batch, channels, size1, size2)
# torch.nn.Conv3D : input shape: (batch, channels, size1, size2, size3)
# parameters
#     torch.nn.Conv2d(in_channels,
#                     out_channels, # Number of filters (K)
#                     kernel_size,  # Filter size (F) -- integer or tuple
#                     stride=1,     # Stride (S) -- (height-bound, width-bound). Can be an integer if they are same.
#                     padding=0,    # Padding (P) -- valid: no padding, same: make the output same as input. Tuple OK.
#                     ...
#                     )

# layer를 적용한 뒤 input shape이 어떻게 바뀌는 지 확인
x = torch.randn(4, 3, 28, 28) 
print(x.shape)
conv = nn.Conv2d(3,2, 3) # (number of channels, number of filters, filter size)
y = conv(x)
print(y.shape)

torch.Size([4, 3, 28, 28])
torch.Size([4, 2, 26, 26])


In [8]:
# ----- nn.RNN -----
# https://pytorch.org/docs/stable/generated/torch.nn.RNN.html
# parameters
#     torch.nn.RNN(input_size,         # Dimensionality of input x
#                   hidden_size,       # Dimensionality of hidden state h
#                   num_layers,        # Number of layers
#                   nonlinearity=relu, # activation function. 디폴트는 relu
#                   bias=False,        # bias 사용 여부. 디폴트는 True
#                   batch_first=True,  # True when input shape is (BATCH, SEQ, EMB), False when input shape is (SEQ, BATCH, EMB)
#                   ...
#                    )

x = torch.randn(5, 64, 10) # (Sequence length, Batch size, Dimensionality of input x)
print(x.shape)
rnn = nn.RNN(10, 20, 2, batch_first=False) # (Dimensionality of input x, Dimensionality of hidden state h, Number of layers)
h0 = torch.randn(2, 64, 20) # (Number of layers, Batch size, Dimensionality of hidden state h) / random initialization
print(h0.shape)
y, h1 = rnn(x, h0)
print(h1.shape)
print(y.shape) # (Sequence length, Batch size, Dimensionality of hidden state h)
fc = nn.Linear(20, 3) # (Dimensionality of hidden state h, Number of classes)
print(fc(y).shape)

torch.Size([5, 64, 10])
torch.Size([2, 64, 20])
torch.Size([2, 64, 20])
torch.Size([5, 64, 20])
torch.Size([5, 64, 3])


In [ ]:
import numpy as np
x = torch.randn(5, 64, 10)
wxh = torch.randn(5, 64, 10)
x.dot(wxh)

In [18]:
# ----- nn.Embedding -----
# https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html
# 임베딩 (Embedding) : 변수를 인코딩할 때 sparse한 one-hot 인코딩 대신 연속적인 값을 가지는 벡터로 표현하는 방법
# 각 카테고리가 나타내는 실수 벡터를 임베딩 벡터라고 함
# parameters
#     torch.nn.Embedding(num_embeddings,    # size of the dictionary of embeddings
#                        embedding_dim,     # the size of each embedding vector
#                        ...
#                         )
input_ = torch.tensor([[1,2,4,5],[4,3,2,9]])
print(input_, input_.shape)
embedding = nn.Embedding(10, 3, padding_idx=0) # 우리가 지정한 dimension으로 Embedding layer 선언
input_ = embedding(input_)
print(input_, input_.shape)
embedding.weight # 임베딩 벡터 확인하기

tensor([[1, 2, 4, 5],
        [4, 3, 2, 9]]) torch.Size([2, 4])
tensor([[[-0.1926, -0.8145,  2.8081],
         [ 0.2051,  0.1417, -0.5687],
         [ 0.6495, -0.1741,  0.7967],
         [ 1.4904,  1.6537, -0.1346]],

        [[ 0.6495, -0.1741,  0.7967],
         [ 0.5102, -0.0068, -0.6989],
         [ 0.2051,  0.1417, -0.5687],
         [-0.3300, -1.2424, -0.0671]]], grad_fn=<EmbeddingBackward0>) torch.Size([2, 4, 3])


Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [-0.1926, -0.8145,  2.8081],
        [ 0.2051,  0.1417, -0.5687],
        [ 0.5102, -0.0068, -0.6989],
        [ 0.6495, -0.1741,  0.7967],
        [ 1.4904,  1.6537, -0.1346],
        [-0.3651, -0.9526,  0.5882],
        [-0.5970,  1.4028,  0.9167],
        [-1.8333, -0.1817, -2.0477],
        [-0.3300, -1.2424, -0.0671]], requires_grad=True)