In [1]:
import numpy as np

In [33]:
# Small Gaussian Random
# : Standard normal distribution, multiplied by a small constant (0.01)
dims = [5] * 5
hs = []
x = np.random.randn(2, dims[0]) # 2x5 matrix
for d_in, d_out in zip(dims[:-1], dims[1:]):
    W = 0.01 * np.random.randn(d_in, d_out) # 5x5 matrix
    x = np.tanh(x.dot(W)) # 2x5 matrix
    hs.append(x)
hs

[array([[ 0.01397684, -0.01537977,  0.01575997, -0.02675083,  0.00984429],
        [-0.00572995,  0.03273013,  0.00354199,  0.00740847,  0.0177547 ]]),
 array([[ 8.96528553e-06, -3.21509462e-04, -1.72025826e-04,
         -1.13993547e-04,  2.38599152e-04],
        [-1.79060427e-04,  3.21360035e-04, -7.29692140e-04,
         -1.19341318e-04,  1.59907368e-04]]),
 array([[ 1.15600723e-06, -4.04669901e-07, -4.78986076e-06,
          1.19551799e-07,  1.61512045e-07],
        [-4.57505979e-06,  5.02397186e-06,  4.15233016e-06,
          3.98359294e-06,  2.18100507e-06]]),
 array([[ 2.32310003e-08,  5.29477342e-08,  8.64100457e-08,
          3.95481761e-08, -2.30444975e-08],
        [-7.69484034e-08,  2.74722287e-08, -1.91109637e-07,
         -9.10884258e-08,  4.16595322e-08]])]

In [34]:
# Large Gaussian Random
# : Since too small weights made all activations to zero, this might solve the issue!
dims = [5] * 5
hs = []
x = np.random.randn(2, dims[0])
for d_in, d_out in zip(dims[:-1], dims[1:]):
    W = 0.5 * np.random.randn(d_in, d_out) 
    x = np.tanh(x.dot(W))
    hs.append(x)
hs

[array([[-0.87320246, -0.99423865, -0.96318167, -0.98660029, -0.68136183],
        [ 0.30609391,  0.32898765,  0.73930982,  0.58737292, -0.40113749]]),
 array([[-0.33297931, -0.88392714, -0.24148869, -0.30695   ,  0.35111313],
        [ 0.45574059,  0.53483635, -0.05904323,  0.0528166 ,  0.26524308]]),
 array([[ 0.6349405 , -0.16345122,  0.01390715,  0.55003052, -0.09518715],
        [-0.39335221,  0.41216361, -0.19154377,  0.26779836, -0.22758251]]),
 array([[-0.7499633 , -0.48631334,  0.3323162 ,  0.41108485,  0.23816768],
        [ 0.29635444, -0.15377107, -0.40676525, -0.00161012,  0.11199849]])]

In [36]:
# Xavier Initialization
# : Just right scale, where activations are nicely scale for all layers
dims = [5] * 5
hs = []
x = np.random.randn(2, dims[0])
for d_in, d_out in zip(dims[:-1], dims[1:]):
    W = np.random.randn(d_in, d_out)/ np.sqrt(d_in) 
    x = np.tanh(x.dot(W))
    hs.append(x)
hs

[array([[ 0.57850006, -0.23721331,  0.52143709,  0.69282749,  0.93277922],
        [ 0.46389015,  0.78475953, -0.14767804,  0.80525948,  0.80872555]]),
 array([[ 0.70740717,  0.62466079, -0.21127398,  0.07476535, -0.38445075],
        [ 0.87957114,  0.47973809,  0.32087946, -0.35208003, -0.16801727]]),
 array([[ 0.30924731, -0.229621  , -0.42562288,  0.24498833, -0.52596424],
        [-0.05178099, -0.05502291, -0.71209579,  0.10329794, -0.31068567]]),
 array([[-0.0972106 ,  0.22631682,  0.23636049,  0.5125563 , -0.09061567],
        [ 0.07909063, -0.03931456,  0.46334625,  0.53249194, -0.09505297]])]

In [37]:
# Weight Initialization for ReLU
dims = [5] * 5
hs = []
x = np.random.randn(2, dims[0])
for d_in, d_out in zip(dims[:-1], dims[1:]):
    W = np.random.randn(d_in, d_out)/ np.sqrt(d_in) 
    x = np.maximum(0, x.dot(W))
    hs.append(x)
hs

[array([[0.85321829, 0.        , 0.54648777, 0.        , 0.        ],
        [0.65392828, 0.64273303, 0.        , 1.0520624 , 0.        ]]),
 array([[0.71466747, 0.43990173, 0.27944149, 0.01182601, 0.        ],
        [0.        , 0.55963239, 0.61440632, 0.        , 0.        ]]),
 array([[0.00937226, 0.        , 0.87952039, 0.08843132, 0.03535586],
        [0.11844519, 0.        , 0.31620861, 0.5618415 , 0.29843078]]),
 array([[0.41324816, 0.29681555, 0.23381608, 0.        , 0.63424444],
        [0.63307843, 0.04363202, 0.        , 0.        , 0.32625321]])]

In [38]:
# Kaiming/MSRA Initialization for ReLU
dims = [5] * 5
hs = []
x = np.random.randn(2, dims[0])
for d_in, d_out in zip(dims[:-1], dims[1:]):
    W = np.random.randn(d_in, d_out) * np.sqrt(2/d_in) 
    x = np.maximum(0, x.dot(W))
    hs.append(x)
hs

[array([[0.        , 0.75066741, 0.81771617, 0.        , 1.78671872],
        [0.45961716, 0.72363105, 0.70620259, 0.51464913, 0.55338823]]),
 array([[0.        , 0.        , 0.07268358, 0.        , 0.        ],
        [0.        , 0.        , 0.81800756, 0.71039799, 0.34807791]]),
 array([[0.        , 0.        , 0.07273109, 0.00289413, 0.10695042],
        [0.        , 0.        , 0.22702348, 0.        , 1.38609184]]),
 array([[0.        , 0.07603674, 0.        , 0.        , 0.        ],
        [0.24909147, 0.69065655, 0.        , 0.        , 0.69801301]])]